### ISSUE TITLE
IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by sachi5908** [ZhiLiHydro/pyRiverBed#1]
+> Trying to read steering file... [done]
MODE 2: READ YOUR OWN RIVER CENTERLINE FROM FILE is selected
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\sachi\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\sachi\Desktop\Py Project\pyRiverBed\gui4pyriverbed.py", line 911, in run
    pyriverbed.main()
  File "C:\Users\sachi\Desktop\Py Project\pyRiverBed\pyriverbed.py", line 1400, in main
    s, x, y, cur, theta = read_centerline(s, x, y, cur, theta)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sachi\Desktop\Py Project\pyRiverBed\pyriverbed.py", line 431, in read_centerline
    mode1 = np.around(mode(np.diff(s))[0][0], decimals=2)
                      ~~~~~~~~~~~~~~~~~~~^^^
IndexError: invalid index to scalar variable.

**Comment by ZhiLiHydro** [comment]
It seems due to an update in scipy.stats.mode. Adding `keepdims=True` might fix the error., i.e., 
mode(np.diff(s)) --> mode(np.diff(s), keepdims=True)

**Comment by sachi5908** [comment]
Thank you ;) Now it's working
